name: Test
on: [push, pull_request]
jobs:
  # -----------------------------------------------------------
  # Deno
  # -----------------------------------------------------------
  Deno:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 2
    strategy:
      matrix:
        node: [20.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: canary

      - name: Build Dual Library
        run: deno task build:dual

      - name: Build Esm Library
        run: deno task build:esm

      - name: Run Bundle Metrics
        run: deno task metrics

      - name: Run Test
        run: deno task test

      - name: Run Report
        run: deno task report
